name: Python Test Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.9 # Gunakan image Python 3.9 seperti di contoh Anda

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3         

      # Step 3: Run tests
      - name: Run tests
        run: python test_app.py # Jalankan pengujian
