name: Python Test Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3         

      - name: Run tests
        run: python test_app.py 
